NeonGeckoCom/skill-alerts

__init__.py, dialog/en-us/ConfirmScript.dialog, dialog/en-us/RecurringScript.dialog, dialog/en-us/ScriptNotFound.dialog, vocab/en-us/script.voc
Addresses #17 
Check whether script exists and emit message to CC to start script
=> FEAT CCL support

__init__.py, settingsmeta.yml, vocab/en-us/priority.voc
=> Feat: manage quiet hours

__init__.py, requirements.txt
Update requirements for Mycroft compat.
Safe import of Tk for Mk2 support
=> Extend NeonSkill class

__init__.py, dialog/en-us/CancelAll.dialog
Clear gui on alert clear
Fix typo in cancel dialog
=> Fix Minor UI Bugs

LICENSE.txt, __init__.py
Refactor Audio alerts
Relicense under BSD-3
=> Refactoring and BSD-Licensing

__init__.py, locale/en-us/dialog/expired_reminder.dialog
Fix typo in repeat alert confirmation
Update expired reminder dialog
=> Minor skill dialog fixes

__init__.py, locale/en-us/dialog/word_weekday.dialog, locale/en-us/dialog/word_weekend.dialog, test/test_skill.py, util/__init__.py
Special case daily, weekday, and weekend alerts dialog
Fix duplicated alerts dialog for repeating alerts
=> Fix and improved handling of speaking repeating alerts

__init__.py, test/test_skill.py, util/alert_manager.py
=> Feat homescreen widgets

__init__.py, requirements.txt, skill.json, test/test_skill.py
Add better timezone handling tests
=> Update default timezone to use method from LF

test/example_messages/alarm_capitalized_vocab.json, test/test_skill.py, util/parse_utils.py
=> Fix tokenize capitalization

requirements.txt, skill.json
Remove ovos-workshop which was added for RuntimeRequirements which moved to ovos-utils
https://github.com/NeonGeckoCom/skill-alerts/pull/74 review
=> Remove leftover ovos-workshop dependency

__init__.py, locale/en-us/intent/list_alerts.intent, test/test_intents.yaml, test/test_resources.yaml, test/test_skill.py
Handle utterances like "what are my reminders" or "do I have any upcoming events"
=> Add padatious intent to handle alternate utterances to query alerts

locale/en-us/vocab/cancel.voc, test/test_intents.yaml
=> Handle "stop timer" as "cancel timer" with intent test

__init__.py
Fixes reported and observed bug where dismissing an active reminder leaves the notification
=> Dismiss alert notification on active alert dismissal

test/test_intents.yaml
Add test cases for failing intents
The reported bugs were likely related to an older version of the skill, but more tests won't hurt in any case.
=> Add failing test cases

locale/en-us/intent/quiet_hours_end.intent, test/test_intents.yaml, test/test_skill.py
Update `quiet_hours_end` intent to handle more cases
Update tests to include reported bugs
Closes #79
=> Update Intents and Tests based on feedback

__init__.py
Handle a "dismiss" request dismissing a displayed timer when GUI is active
Closes #101
=> Handle "dismiss" request with active timer

__init__.py
Explicitly release GUI when an active alert is dismissed via voice
Closes #100
=> Release GUI on alert dismissal (converse)

__init__.py, test/test_skill.py
Implement snooze on alert expiration with duration and time support
Closes #106
=> Implement "snooze" for active alerts

.github/workflows/skill_tests.yml, __init__.py, locale/en-us/intent/list_alerts.intent, util/parse_utils.py
Troubleshoot missing intent data in `CreateReminderAlt`
=> Troubleshoot repeat intent

__init__.py, requirements.txt, skill.json
Implement ovos_bus_client instead of mycroft-messagebus-client
Refactor imports to new best practices
Closes #111
=> Update dependencies and import references

__init__.py
Deprecate `create_skill` method
Update `__init__` for best practices
Update skill settings references
=> Update for best practices

__init__.py
Reorg `__init__` for ovos-workshop compat.
=> Reafctor skill init/initialize

__init__.py, settingsmeta.yml, setup.py
Updates resource file resolution for alert sound files
Also implements `escalate_volume` skill setting that increases volume while an alert is active and resumes initial volume when the alert is dismissed or missed
Closes #125
=> Refactor resource resolution to resolve default sound errors

__init__.py
=> Update to default escalating volume True for alarms to be audible

__init__.py, requirements/test.txt
Moves deprecation notice to 4.0.0 since it will be included starting with 3.0.0
Updates test dependencies to stable versions
=> Update log and test requirements to prep release

.github/workflows/update_skill_json.yml, .gitignore, LICENSE.md, __init__.py, requirements.txt, requirements/test.txt, setup.py, skill.json, test/test_skill.py, util/__init__.py, util/alert.py, util/alert_manager.py, util/parse_utils.py, util/ui_models.py, version.py
Update skill.json workflow branches-ignore
Standardize gitignore
Update License Notices to 2025
Includes fix for ovos-utils 0.1+ compat. in unit tests
=> Update automation, gitignore, and license notices
